export default styles = {
    main:{
        flex:1,
        flexDirection: 'row',
    },
    scroll:{
        flex:1,
        backgroundColor:'#f7f7f7',
    },
    header:{
        paddingBottom:15,
        marginBottom:15,
        backgroundColor:'#ffffff',
    },
    headerImage:{
        height:70,
        marginTop:25,
        alignItems:'center',
    },
    headerImageIcon:{
        height:70,
        width:70,
        borderRadius:35,
    },
    headerName:{
        height:30,
        marginTop:10,
        marginBottom:0,
        alignItems:'center',
        justifyContent:'center',
    },
    headerNameText:{
        fontSize:16,
        color:"#545454",
    },
    headerDesc:{
        paddingLeft:15,
        paddingRight:15,
        alignItems:'center',
        maxHeight:45,
        overflow:"hidden",
    },
    headerDescText:{
        fontSize:14,
        color:"#999",
        lineHeight:21,
    },
    bottomView:{
        marginTop:10,
    },
    logoutView:{
        marginTop:10,
        marginBottom:20,
    },
    button:{
        height:50,
        borderBottomColor:'#f1f1f1',
        borderBottomWidth:1,
        borderStyle:'solid',
        backgroundColor:'#ffffff',
        justifyContent:'center',
        paddingLeft:20,
    },
    buttonText:{
        fontSize:16,
        color:"#666666",
    },
    logoutButton:{
        height:50,
        borderBottomColor:'#f1f1f1',
        borderBottomWidth:1,
        borderStyle:'solid',
        backgroundColor:'#ffffff',
        justifyContent:'center',
        alignItems:"center"
    },
    logoutButtonText:{
        fontSize:16,
        color:"#F44336",
    }
}
